### ISSUE TITLE
Hero items return the incorrect values for next upgrade and max upgrade.

### ISSUE THREAD

**Issue by arcadepro** [filliph/ItemUpgradeTip#1]
### Description

The numerical ilvl values/strings seem to be incorrect. 
Cost for next level (INCORRECT ILVL)
Cost to upgrade to max level (INCORRECT ILVL)

The crest and flightstone costs seem to be correct.

Examples:

This only seems to be an issue with 'Hero' level items.

![image](https://github.com/filliph/ItemUpgradeTip/assets/1977760/09984068-3821-4759-9b09-9382a7458c3a)
![image](https://github.com/filliph/ItemUpgradeTip/assets/1977760/d1fc87c7-f244-4c28-80ad-9347a3fc2b14)

### World of Warcraft Flavor

Retail (Default)

### ItemUpgradeTip Version

1.2.2

### Tested with only ItemUpgradeTip

Yes

**Comment by filliph** [comment]
Fixed in https://github.com/filliph/ItemUpgradeTip/commit/c9b5f1fb9efb637c430564464a730d6688ad6915 and pushed with v1.2.2, thanks 😄
