### ISSUE TITLE
Does not function on zhTW clients

### ISSUE THREAD

**Issue by filliph** [filliph/ItemUpgradeTip#2]
The tooltip integration does not appear to function on zhTW clients. See screenshot: https://upload.cc/i1/2023/05/31/5xy78D.jpg

**Comment by nanjuekaien1** [comment]
It does not work on zhCN

**Comment by filliph** [comment]
I'm investigating; I suspect it has to do with Unicode. I'm actively working on it and hopefully, I will have an update soon.

Sorry for the inconvenience 🙁

**Comment by filliph** [comment]
Should be fixed in v1.5.2 which is currently being deployed.

**Comment by nanjuekaien1** [comment]
v1.5.2  There is no error reported.
