### ISSUE TITLE
zhCN

### ISSUE THREAD

**Issue by nanjuekaien1** [filliph/ItemUpgradeTip#26]
### Is your feature request related to a problem? Please describe.

L["MODIFIER_KEY"] = "快捷键"
L["MODIFIER_KEY_DESC"] = "如果启用，则必须按住此键才能启用鼠标提示整合。"
L["UPGRADE_TRACK_ADVENTURER"] = "冒险者"

### Describe the solution you'd like

How can I submit a localisation in the future?

**Comment by filliph** [comment]
You'll need an account @ CurseForge and then I can add you as a Translator :)

Let me know your username @ CF and I can add you.

**Comment by nanjuekaien1** [comment]
I sent you a text message from inside Curseforge.
^_^

**Comment by nanjuekaien1** [comment]
Unable to add
![屏幕截图 2024-01-19 210627](https://github.com/filliph/ItemUpgradeTip/assets/2303601/6b4803fd-40c1-48ba-a1ae-cd01b5d93d30)

L["MODIFIER_KEY"] = "快捷键"
L["MODIFIER_KEY_DESC"] = "如果启用，则必须按住此键才能启用鼠标提示整合。"
L["UPGRADE_TRACK_ADVENTURER"] = "冒险者"

**Comment by nanjuekaien1** [comment]
My mistake: What you were given was the name shown... 
The username is: nanjuekaien
