### ISSUE TITLE
Season 4 update

### ISSUE THREAD

**Issue by filliph** [filliph/ItemUpgradeTip#29]
Update ilvls / bonusIDs for Season 4.

**Comment by nanjuekaien1** [comment]
When will the Season 4 version be released?

**Comment by chris-rowley83** [comment]
Season 4 update would be nice

**Comment by add1kted2ka0s** [comment]
+1 to this - love this addon

**Comment by filliph** [comment]
I don't have an ETA yet as I was not able to pre-compile all the data on the PTR. I'm currently out of the office travelling so I cannot finish the update yet.
